services:
  web:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      SERVICE: web
    volumes:
      - media_data:/app/media
      - static_data:/app/staticfiles
    ports:
      - "8010:8000"
    networks:
      - dokploy-network

  worker:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      SERVICE: worker
    volumes:
      - media_data:/app/media
    networks:
      - dokploy-network

volumes:
  media_data:
  static_data:

networks:
  dokploy-network:
    external: true
