[pytest]
DJANGO_SETTINGS_MODULE = clasica_project.settings.base
python_files = tests.py test_*.py
python_classes = Test*
python_functions = test_*
testpaths = apps
addopts = -v --tb=short
markers =
    unit: Tests que no requieren base de datos
