# Generated by Django 6.0.5 on 2026-05-08 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('open', 'Open / Elite'), ('m40', 'Master 40'), ('m50', 'Master 50'), ('m60', 'Master 60+')], db_index=True, default='open', max_length=10)),
                ('position_overall', models.PositiveIntegerField(blank=True, null=True)),
                ('position_category', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='participations.participation')),
            ],
            options={
                'verbose_name': 'Clasificación',
                'verbose_name_plural': 'Clasificaciones',
                'ordering': ['position_overall'],
            },
        ),
    ]
