# Generated by Django 6.0.5 on 2026-05-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('route_gpx', models.FileField(blank=True, null=True, upload_to='routes/gpx/')),
                ('route_geojson', models.JSONField(blank=True, null=True)),
                ('route_distance_km', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada'), ('results_published', 'Resultados publicados')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Edición',
                'verbose_name_plural': 'Ediciones',
                'ordering': ['-date'],
            },
        ),
    ]
