# Generated by Django 6.0.5 on 2026-05-08 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Foto'), ('video', 'Vídeo')], max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='editions/media/')),
                ('video_url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='editions.edition')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
