# Generated by Django 6.0.5 on 2026-05-09 10:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0004_remove_edition_route_geojson_edition_route_geometry'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('route_gpx', models.FileField(upload_to='variants/gpx/')),
                ('route_geometry', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('route_distance_km', models.FloatField(blank=True, null=True)),
                ('elevation_profile', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Variante de Ruta',
                'verbose_name_plural': 'Variantes de Ruta',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='edition',
            name='elevation_profile',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='route_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editions', to='editions.routevariant'),
        ),
    ]
