# Generated by Django 6.0.5 on 2026-05-09 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0005_routevariant_edition_elevation_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='start_time',
            field=models.TimeField(default=datetime.time(16, 30), verbose_name='Hora de salida'),
        ),
    ]
