# Generated by Django 6.0.5 on 2026-05-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0006_edition_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edition',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Edición', 'verbose_name_plural': 'Ediciones'},
        ),
    ]
