# Generated by Django 6.0.5 on 2026-05-08 11:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='editions.edition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['registered_at'],
                'unique_together': {('user', 'edition')},
            },
        ),
        migrations.CreateModel(
            name='StravaActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_activity_id', models.BigIntegerField(db_index=True, unique=True)),
                ('elapsed_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('track_geojson', models.JSONField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('validation_score', models.FloatField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strava_activity', to='participations.participation')),
            ],
            options={
                'verbose_name': 'Actividad Strava',
                'verbose_name_plural': 'Actividades Strava',
            },
        ),
    ]
