# Generated by Django 6.0.5 on 2026-05-09 09:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stravaactivity',
            name='track_geojson',
        ),
        migrations.AddField(
            model_name='stravaactivity',
            name='track_geometry',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
