# Generated by Django 6.0.5 on 2026-05-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0003_rename_stravaactivity_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='average_moving_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
