# Generated by Django 6.0.5 on 2026-05-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0004_add_average_moving_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='track_geometry',
        ),
    ]
